[2025-01-23T13:37:42.225+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_airflow.etl_task manual__2025-01-23T12:14:19.972456+00:00 [queued]>
[2025-01-23T13:37:42.232+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_airflow.etl_task manual__2025-01-23T12:14:19.972456+00:00 [queued]>
[2025-01-23T13:37:42.233+0000] {taskinstance.py:1361} INFO - Starting attempt 12 of 13
[2025-01-23T13:37:42.241+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): etl_task> on 2025-01-23 12:14:19.972456+00:00
[2025-01-23T13:37:42.245+0000] {standard_task_runner.py:57} INFO - Started process 447 to run task
[2025-01-23T13:37:42.247+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'hello_***', 'etl_task', 'manual__2025-01-23T12:14:19.972456+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpgyhnts4e']
[2025-01-23T13:37:42.248+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask etl_task
[2025-01-23T13:37:42.282+0000] {task_command.py:415} INFO - Running <TaskInstance: hello_airflow.etl_task manual__2025-01-23T12:14:19.972456+00:00 [running]> on host d2c53ae28a1f
[2025-01-23T13:37:42.333+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hello_***' AIRFLOW_CTX_TASK_ID='etl_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-23T12:14:19.972456+00:00' AIRFLOW_CTX_TRY_NUMBER='12' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-23T12:14:19.972456+00:00'
[2025-01-23T13:37:42.333+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-23T13:37:42.334+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/etl.py']
[2025-01-23T13:37:42.339+0000] {subprocess.py:86} INFO - Output:
[2025-01-23T13:37:42.400+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-01-23T13:37:42.400+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/etl.py", line 1, in <module>
[2025-01-23T13:37:42.400+0000] {subprocess.py:93} INFO -     from pyspark.sql import SparkSession,functions as func
[2025-01-23T13:37:42.400+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'pyspark'
[2025-01-23T13:37:42.402+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-01-23T13:37:42.408+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-23T13:37:42.411+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=hello_***, task_id=etl_task, execution_date=20250123T121419, start_date=20250123T133742, end_date=20250123T133742
[2025-01-23T13:37:42.422+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 22 for task etl_task (Bash command failed. The command returned a non-zero exit code 1.; 447)
[2025-01-23T13:37:42.460+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-23T13:37:42.482+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
